application: itemcatalog-163806
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets/
  static_dir: stylesheets

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img

- url: /.*
  script: itemcatalog.app

libraries:
- name: jinja2
  version: latest